spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${eureka.security.username}
      password: ${eureka.security.password}

eureka:
  client:
    fetchRegistry: false
  server:
    enableSelfPreservation: false