server:
  port: 8000

spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: ws123456

eureka:
  instance:
    # 指定该Eureka实例的主机名
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false